"""
==============================================================================
  MEMBER 2: GNN Model Training Pipeline
  Graph Neural Network for Malware Classification
==============================================================================
Purpose:
  - Loads graph data generated by Member 3 (data_to_graph.py)
  - Trains GCN/GAT models on malware sample graphs
  - Evaluates on test set and outputs predictions in Prospect/Aspect/Context format
  - Compatible with Member 1's autonomous agent orchestration
==============================================================================
"""

import os
import json
import numpy as np
import pandas as pd
import pickle
import joblib
import datetime
import warnings
from collections import defaultdict

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torch_geometric
from torch_geometric.data import Data, DataLoader as GeoDataLoader
from torch_geometric.nn import GCNConv, GATConv, global_mean_pool, global_add_pool
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, roc_auc_score, roc_curve
)
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

# ─────────────────────────────────────────────────────────────────────────────
# 0. CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────

OUTPUT_DIR = f"model/gnn_outputs_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}"
GRAPH_DATA_DIR = "graph_output"  # Member 3's output directory (in root)
BATCH_SIZE = 32
NUM_EPOCHS = 50
LEARNING_RATE = 0.001
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
MODEL_TYPE = "GCN"  # Options: "GCN", "GAT"
HIDDEN_DIM = 64
DROPOUT = 0.3

# Create output directory
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

print(f"[INFO] Using device: {DEVICE}")
print(f"[INFO] Output directory: {OUTPUT_DIR}")

# ─────────────────────────────────────────────────────────────────────────────
# 1. GRAPH DATA LOADING (From Member 3's Output)
# ─────────────────────────────────────────────────────────────────────────────

class MalwareGraphDataset(Dataset):
    """
    Dataset class for loading graph data from Member 3's data_to_graph.py output
    
    Expected structure:
    - GRAPH_DATA_DIR/graph_metadata.json: {graph_id: {filename, label}}
    - GRAPH_DATA_DIR/graphs/{graph_id}.json: NetworkX node-link format
    """
    
    def __init__(self, graph_dir, metadata_file, split="train", test_size=0.2, 
                 random_state=42, train_ratio=0.8):
        """
        Args:
            graph_dir: Directory containing graph JSON files
            metadata_file: Path to graph_metadata.json
            split: "train" or "test"
            test_size: Proportion for test split
            random_state: For reproducibility
            train_ratio: Ratio of training data in training split
        """
        self.graph_dir = graph_dir
        self.split = split
        self.graphs = []
        self.labels = []
        self.label_encoder = None
        
        # Load metadata
        with open(metadata_file, 'r') as f:
            self.metadata = json.load(f)
        
        # Get all graph IDs and their labels
        graph_ids = list(self.metadata.keys())
        labels = [self.metadata[gid]['label'] for gid in graph_ids]
        
        # Split into train/test (80% train, 20% test)
        train_ids, test_ids = train_test_split(
            graph_ids, test_size=test_size, random_state=random_state,
            stratify=labels
        )
        
        # Encode labels
        self.label_encoder = LabelEncoder()
        self.label_encoder.fit(labels)
        
        # Select split
        selected_ids = train_ids if split == "train" else test_ids
        
        # Load graphs
        print(f"[INFO] Loading {split} graphs ({len(selected_ids)} samples)...")
        for i, graph_id in enumerate(selected_ids):
            graph_path = os.path.join(graph_dir, "graphs", f"{graph_id}.json")
            
            if not os.path.exists(graph_path):
                print(f"[WARNING] Graph file not found: {graph_path}")
                continue
            
            try:
                with open(graph_path, 'r') as f:
                    graph_data = json.load(f)
                
                label = self.metadata[graph_id]['label']
                self.graphs.append(graph_data)
                self.labels.append(self.label_encoder.transform([label])[0])
                
                if (i + 1) % 1000 == 0:
                    print(f"[INFO] Loaded {i + 1}/{len(selected_ids)} graphs")
            
            except Exception as e:
                print(f"[ERROR] Failed to load {graph_path}: {str(e)}")
                continue
        
        print(f"[INFO] Successfully loaded {len(self.graphs)} graphs for {split} split")
    
    def __len__(self):
        return len(self.graphs)
    
    def __getitem__(self, idx):
        """Convert graph JSON to PyTorch Geometric Data object"""
        graph_data = self.graphs[idx]
        label = self.labels[idx]
        
        # Extract nodes and edges from node-link format
        nodes = {n['id']: n for n in graph_data['nodes']}
        
        # Create node feature matrix (one-hot encoding of node types)
        node_types = list(set([n['type'] for n in graph_data['nodes']]))
        type_to_idx = {t: i for i, t in enumerate(node_types)}
        
        num_nodes = len(nodes)
        num_types = len(node_types)
        
        # Node features: one-hot encoding of node type
        x = np.zeros((num_nodes, num_types), dtype=np.float32)
        node_id_to_idx = {}
        
        for i, (node_id, node) in enumerate(sorted(nodes.items())):
            node_id_to_idx[node_id] = i
            node_type = node['type']
            x[i, type_to_idx[node_type]] = 1.0
        
        # Edge list
        edge_list = []
        for edge in graph_data['links']:
            source_idx = node_id_to_idx.get(edge['source'])
            target_idx = node_id_to_idx.get(edge['target'])
            
            if source_idx is not None and target_idx is not None:
                # Add both directions for undirected graph
                edge_list.append([source_idx, target_idx])
                edge_list.append([target_idx, source_idx])
        
        if edge_list:
            edge_index = np.array(edge_list, dtype=np.int64).T
        else:
            # Handle isolated nodes
            edge_index = np.array([[], []], dtype=np.int64)
        
        # Convert to PyTorch tensors
        x = torch.tensor(x, dtype=torch.float32)
        edge_index = torch.tensor(edge_index, dtype=torch.long)
        y = torch.tensor(label, dtype=torch.long)
        
        # Create PyTorch Geometric Data object
        data = Data(x=x, edge_index=edge_index, y=y)
        
        return data
    
    def get_num_classes(self):
        return len(self.label_encoder.classes_)
    
    def get_class_names(self):
        return self.label_encoder.classes_


# ─────────────────────────────────────────────────────────────────────────────
# 2. GNN MODELS
# ─────────────────────────────────────────────────────────────────────────────

class GCNModel(nn.Module):
    """Graph Convolutional Network (GCN) for malware classification"""
    
    def __init__(self, input_dim, hidden_dim, output_dim, dropout=0.3):
        super(GCNModel, self).__init__()
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.conv3 = GCNConv(hidden_dim, hidden_dim)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.dropout = nn.Dropout(dropout)
        self.relu = nn.ReLU()
    
    def forward(self, x, edge_index, batch):
        """
        Args:
            x: Node features [num_nodes, input_dim]
            edge_index: Edge indices [2, num_edges]
            batch: Batch assignment vector [num_nodes]
        """
        # GCN layers with ReLU activation
        x = self.relu(self.conv1(x, edge_index))
        x = self.dropout(x)
        x = self.relu(self.conv2(x, edge_index))
        x = self.dropout(x)
        x = self.relu(self.conv3(x, edge_index))
        
        # Global mean pooling (aggregate node representations per graph)
        x = global_mean_pool(x, batch)
        
        # Classification layer
        x = self.fc(x)
        return x


class GATModel(nn.Module):
    """Graph Attention Network (GAT) for malware classification"""
    
    def __init__(self, input_dim, hidden_dim, output_dim, num_heads=4, dropout=0.3):
        super(GATModel, self).__init__()
        self.conv1 = GATConv(input_dim, hidden_dim, heads=num_heads, dropout=dropout)
        self.conv2 = GATConv(hidden_dim * num_heads, hidden_dim, heads=num_heads, dropout=dropout)
        self.conv3 = GATConv(hidden_dim * num_heads, hidden_dim, heads=1, dropout=dropout)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.dropout = nn.Dropout(dropout)
        self.relu = nn.ReLU()
    
    def forward(self, x, edge_index, batch):
        """
        Args:
            x: Node features [num_nodes, input_dim]
            edge_index: Edge indices [2, num_edges]
            batch: Batch assignment vector [num_nodes]
        """
        # GAT layers with ReLU activation
        x = self.relu(self.conv1(x, edge_index))
        x = self.dropout(x)
        x = self.relu(self.conv2(x, edge_index))
        x = self.dropout(x)
        x = self.conv3(x, edge_index)
        
        # Global mean pooling
        x = global_mean_pool(x, batch)
        
        # Classification layer
        x = self.fc(x)
        return x


# ─────────────────────────────────────────────────────────────────────────────
# 3. TRAINING FUNCTIONS
# ─────────────────────────────────────────────────────────────────────────────

def train_epoch(model, train_loader, optimizer, criterion, device):
    """Train for one epoch"""
    model.train()
    total_loss = 0
    correct = 0
    total = 0
    
    for batch in train_loader:
        batch = batch.to(device)
        optimizer.zero_grad()
        
        out = model(batch.x, batch.edge_index, batch.batch)
        loss = criterion(out, batch.y)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        pred = out.argmax(dim=1)
        correct += (pred == batch.y).sum().item()
        total += batch.y.size(0)
    
    avg_loss = total_loss / len(train_loader)
    accuracy = correct / total
    return avg_loss, accuracy


def evaluate(model, test_loader, criterion, device):
    """Evaluate model on test set"""
    model.eval()
    total_loss = 0
    correct = 0
    total = 0
    all_preds = []
    all_labels = []
    all_probs = []
    
    with torch.no_grad():
        for batch in test_loader:
            batch = batch.to(device)
            out = model(batch.x, batch.edge_index, batch.batch)
            loss = criterion(out, batch.y)
            
            total_loss += loss.item()
            pred = out.argmax(dim=1)
            correct += (pred == batch.y).sum().item()
            total += batch.y.size(0)
            
            all_preds.extend(pred.cpu().numpy())
            all_labels.extend(batch.y.cpu().numpy())
            
            # Get probabilities for ROC-AUC
            probs = torch.softmax(out, dim=1)
            all_probs.extend(probs.cpu().numpy())
    
    avg_loss = total_loss / len(test_loader)
    accuracy = correct / total
    
    return avg_loss, accuracy, np.array(all_preds), np.array(all_labels), np.array(all_probs)


# ─────────────────────────────────────────────────────────────────────────────
# 4. MAIN TRAINING PIPELINE
# ─────────────────────────────────────────────────────────────────────────────

def main():
    """Main training pipeline"""
    
    print("[STEP 1] Loading graph dataset...")
    try:
        # Check if graph data exists
        if not os.path.exists(os.path.join(GRAPH_DATA_DIR, "graph_metadata.json")):
            print(f"[ERROR] Graph metadata not found at {GRAPH_DATA_DIR}")
            print("[INFO] Please run Member 3's data_to_graph.py first to generate graphs")
            print(f"[INFO] Expected: {os.path.join(GRAPH_DATA_DIR, 'graph_metadata.json')}")
            return
        
        # Load training and test datasets
        train_dataset = MalwareGraphDataset(
            graph_dir=GRAPH_DATA_DIR,
            metadata_file=os.path.join(GRAPH_DATA_DIR, "graph_metadata.json"),
            split="train"
        )
        
        test_dataset = MalwareGraphDataset(
            graph_dir=GRAPH_DATA_DIR,
            metadata_file=os.path.join(GRAPH_DATA_DIR, "graph_metadata.json"),
            split="test"
        )
        
        num_classes = train_dataset.get_num_classes()
        class_names = train_dataset.get_class_names()
        
        print(f"[INFO] Training samples: {len(train_dataset)}")
        print(f"[INFO] Test samples: {len(test_dataset)}")
        print(f"[INFO] Number of classes: {num_classes}")
        print(f"[INFO] Classes: {class_names}")
        
    except Exception as e:
        print(f"[ERROR] Failed to load dataset: {str(e)}")
        return
    
    print("\n[STEP 2] Creating data loaders...")
    train_loader = GeoDataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
    test_loader = GeoDataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)
    
    # Get input dimension from first batch
    sample_batch = next(iter(train_loader))
    input_dim = sample_batch.x.shape[1]
    print(f"[INFO] Input feature dimension (node types): {input_dim}")
    
    print(f"\n[STEP 3] Initializing {MODEL_TYPE} model...")
    if MODEL_TYPE == "GCN":
        model = GCNModel(
            input_dim=input_dim,
            hidden_dim=HIDDEN_DIM,
            output_dim=num_classes,
            dropout=DROPOUT
        )
    elif MODEL_TYPE == "GAT":
        model = GATModel(
            input_dim=input_dim,
            hidden_dim=HIDDEN_DIM,
            output_dim=num_classes,
            dropout=DROPOUT
        )
    else:
        raise ValueError(f"Unknown model type: {MODEL_TYPE}")
    
    model = model.to(DEVICE)
    print(f"[INFO] Model parameters: {sum(p.numel() for p in model.parameters()):,}")
    
    # Optimizer and loss function
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
    criterion = nn.CrossEntropyLoss()
    
    print(f"\n[STEP 4] Training for {NUM_EPOCHS} epochs...")
    train_losses = []
    train_accs = []
    test_losses = []
    test_accs = []
    
    best_test_acc = 0
    best_model_path = os.path.join(OUTPUT_DIR, "best_model.pt")
    
    for epoch in range(NUM_EPOCHS):
        train_loss, train_acc = train_epoch(model, train_loader, optimizer, criterion, DEVICE)
        test_loss, test_acc, _, _, _ = evaluate(model, test_loader, criterion, DEVICE)
        
        train_losses.append(train_loss)
        train_accs.append(train_acc)
        test_losses.append(test_loss)
        test_accs.append(test_acc)
        
        # Save best model
        if test_acc > best_test_acc:
            best_test_acc = test_acc
            torch.save(model.state_dict(), best_model_path)
        
        if (epoch + 1) % 10 == 0:
            print(f"Epoch {epoch+1:03d} | "
                  f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f} | "
                  f"Test Loss: {test_loss:.4f}, Test Acc: {test_acc:.4f}")
    
    print(f"\n[STEP 5] Loading best model and evaluating...")
    model.load_state_dict(torch.load(best_model_path))
    test_loss, test_acc, preds, labels, probs = evaluate(model, test_loader, criterion, DEVICE)
    
    print(f"[INFO] Final Test Accuracy: {test_acc:.4f}")
    print(f"[INFO] Final Test Loss: {test_loss:.4f}")
    
    # Calculate metrics
    precision = precision_score(labels, preds, average='macro', zero_division=0)
    recall = recall_score(labels, preds, average='macro', zero_division=0)
    f1 = f1_score(labels, preds, average='macro', zero_division=0)
    
    print(f"[INFO] Precision (macro): {precision:.4f}")
    print(f"[INFO] Recall (macro): {recall:.4f}")
    print(f"[INFO] F1-Score (macro): {f1:.4f}")
    
    print(f"\n[STEP 6] Saving results and artifacts...")
    
    # Save model
    model_path = os.path.join(OUTPUT_DIR, "model_final.pt")
    torch.save(model.state_dict(), model_path)
    print(f"[INFO] Model saved to {model_path}")
    
    # Save training history
    history = {
        'train_loss': train_losses,
        'train_acc': train_accs,
        'test_loss': test_losses,
        'test_acc': test_accs
    }
    history_path = os.path.join(OUTPUT_DIR, "training_history.json")
    with open(history_path, 'w') as f:
        json.dump(history, f)
    print(f"[INFO] Training history saved to {history_path}")
    
    # Save predictions in Member 1 compatible format (Prospect/Aspect/Context)
    predictions_json = {
        'model_type': MODEL_TYPE,
        'accuracy': float(test_acc),
        'precision': float(precision),
        'recall': float(recall),
        'f1_score': float(f1),
        'num_test_samples': len(labels),
        'class_names': list(class_names),
        'predictions': []
    }
    
    for i in range(len(labels)):
        pred_entry = {
            'true_label': str(class_names[labels[i]]),
            'predicted_label': str(class_names[preds[i]]),
            'confidence': float(probs[i, preds[i]]),
            'all_class_probabilities': {
                class_names[j]: float(probs[i, j])
                for j in range(num_classes)
            },
            'prospect': {
                'predicted_malware_type': str(class_names[preds[i]]),
                'confidence_score': float(probs[i, preds[i]])
            },
            'aspect': {
                'feature_vector': 'See node embeddings in advanced output',
                'graph_structure_features': 'Available in detailed analysis'
            },
            'context': {
                'true_label': str(class_names[labels[i]]),
                'prediction_correct': bool(preds[i] == labels[i]),
                'evaluation_set': 'test'
            }
        }
        predictions_json['predictions'].append(pred_entry)
    
    predictions_path = os.path.join(OUTPUT_DIR, "gnn_predictions.json")
    with open(predictions_path, 'w') as f:
        json.dump(predictions_json, f, indent=2)
    print(f"[INFO] Predictions saved to {predictions_path}")
    
    # Plot training history
    plt.figure(figsize=(12, 5))
    
    plt.subplot(1, 2, 1)
    plt.plot(train_losses, label='Train Loss')
    plt.plot(test_losses, label='Test Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Training History - Loss')
    plt.legend()
    plt.grid(True)
    
    plt.subplot(1, 2, 2)
    plt.plot(train_accs, label='Train Accuracy')
    plt.plot(test_accs, label='Test Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.title('Training History - Accuracy')
    plt.legend()
    plt.grid(True)
    
    history_plot_path = os.path.join(OUTPUT_DIR, "training_history.png")
    plt.savefig(history_plot_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"[INFO] Training history plot saved to {history_plot_path}")
    
    # Plot confusion matrix
    cm = confusion_matrix(labels, preds)
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', xticklabels=class_names, yticklabels=class_names)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.title('Confusion Matrix')
    cm_plot_path = os.path.join(OUTPUT_DIR, "confusion_matrix.png")
    plt.savefig(cm_plot_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"[INFO] Confusion matrix plot saved to {cm_plot_path}")
    
    # Save summary
    summary = {
        'model_type': MODEL_TYPE,
        'config': {
            'batch_size': BATCH_SIZE,
            'num_epochs': NUM_EPOCHS,
            'learning_rate': LEARNING_RATE,
            'hidden_dim': HIDDEN_DIM,
            'dropout': DROPOUT
        },
        'results': {
            'test_accuracy': float(test_acc),
            'test_loss': float(test_loss),
            'precision': float(precision),
            'recall': float(recall),
            'f1_score': float(f1),
            'num_test_samples': len(labels),
            'num_classes': num_classes
        }
    }
    
    summary_path = os.path.join(OUTPUT_DIR, "summary.json")
    with open(summary_path, 'w') as f:
        json.dump(summary, f, indent=2)
    print(f"[INFO] Summary saved to {summary_path}")
    
    print(f"\n[COMPLETE] Training finished!")
    print(f"[INFO] All outputs saved to {OUTPUT_DIR}")
    print(f"[INFO] Use gnn_predictions.json output for Member 1's agent orchestration")


if __name__ == "__main__":
    main()
